package com.dao;

import com.pojo.LzAccount;

public interface LzAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_account
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int deleteByPrimaryKey(Integer accountid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_account
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int insert(LzAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_account
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int insertSelective(LzAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_account
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    LzAccount selectByPrimaryKey(Integer accountid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_account
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int updateByPrimaryKeySelective(LzAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_account
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int updateByPrimaryKey(LzAccount record);
}