package com.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.pojo.LzActivecode;

public interface LzActivecodeMapper {
	
	@Select("${sql}")
	public List<LzActivecode> selectBySql(@Param("sql") String sql);
	
	@Select("${sql}")
	public int selectCountBySql(@Param("sql") String sql);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_activecode
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int deleteByPrimaryKey(Integer activeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_activecode
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int insert(LzActivecode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_activecode
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int insertSelective(LzActivecode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_activecode
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    LzActivecode selectByPrimaryKey(Integer activeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_activecode
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int updateByPrimaryKeySelective(LzActivecode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_activecode
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int updateByPrimaryKey(LzActivecode record);
}