package com.dao;

import com.pojo.LzDayaccount;

public interface LzDayaccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_dayaccount
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int deleteByPrimaryKey(Integer dayid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_dayaccount
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int insert(LzDayaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_dayaccount
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int insertSelective(LzDayaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_dayaccount
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    LzDayaccount selectByPrimaryKey(Integer dayid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_dayaccount
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int updateByPrimaryKeySelective(LzDayaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_dayaccount
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int updateByPrimaryKey(LzDayaccount record);
}