package com.dao;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.pojo.LzDealorder;

public interface LzDealorderMapper {
	
	@Select("${sql}")
	public List<LzDealorder> selectBySql(@Param("sql") String sql);
	@Select("select sum(Dealamount) from lz_dealorder where gameid=#{gameid}")
	public BigDecimal getSumMoneyByGameId(@Param("gameid") int gameid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_dealorder
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int deleteByPrimaryKey(Integer dealid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_dealorder
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int insert(LzDealorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_dealorder
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int insertSelective(LzDealorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_dealorder
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    LzDealorder selectByPrimaryKey(Integer dealid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_dealorder
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int updateByPrimaryKeySelective(LzDealorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_dealorder
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int updateByPrimaryKey(LzDealorder record);
}