package com.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.pojo.LzDialset;
import com.pojo.UserDialRecode;

public interface LzDialsetMapper {
	@Select("select Dealtype,Dealamount,dealtime from lz_dealorder where Dealtype=3 and dealphone=#{phone} union all select dealtype,weight,dealtime from lz_weightaccount where Dealtype=2 and phone=#{phone} order by dealtime desc")
	List<UserDialRecode> getUserDialRecode(@Param("phone") String phone); 
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_dialset
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int deleteByPrimaryKey(Integer dialid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_dialset
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int insert(LzDialset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_dialset
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int insertSelective(LzDialset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_dialset
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    LzDialset selectByPrimaryKey(Integer dialid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_dialset
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int updateByPrimaryKeySelective(LzDialset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_dialset
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int updateByPrimaryKey(LzDialset record);
}