package com.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.pojo.LzFriendlist;

public interface LzFriendlistMapper {
	@Select("${sql}")
	List<Map<String, Object>> findMapBysql(@Param("sql") String sql);
	
	@Select("${sql}")
	List<LzFriendlist> findBySql(@Param("sql") String sql);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_friendlist
     *
     * @mbg.generated Thu Aug 29 17:59:22 CST 2019
     */
    int deleteByPrimaryKey(Integer flid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_friendlist
     *
     * @mbg.generated Thu Aug 29 17:59:22 CST 2019
     */
    int insert(LzFriendlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_friendlist
     *
     * @mbg.generated Thu Aug 29 17:59:22 CST 2019
     */
    int insertSelective(LzFriendlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_friendlist
     *
     * @mbg.generated Thu Aug 29 17:59:22 CST 2019
     */
    LzFriendlist selectByPrimaryKey(Integer flid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_friendlist
     *
     * @mbg.generated Thu Aug 29 17:59:22 CST 2019
     */
    int updateByPrimaryKeySelective(LzFriendlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_friendlist
     *
     * @mbg.generated Thu Aug 29 17:59:22 CST 2019
     */
    int updateByPrimaryKey(LzFriendlist record);
}