package com.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.pojo.LzGameround;

public interface LzGameroundMapper {
	@Update("update lz_gameround set status='2' where status='1'")
	public void setGameInvalid();
	
	@Select("${sql}")
	public List<LzGameround> selectGameRoundBySql(@Param("sql") String sql);
	
	@Select("${sql}")
	public int selectCountBySql(@Param("sql") String sql);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_gameround
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    int deleteByPrimaryKey(Integer gameid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_gameround
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    int insert(LzGameround record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_gameround
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    int insertSelective(LzGameround record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_gameround
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    LzGameround selectByPrimaryKey(Integer gameid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_gameround
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    int updateByPrimaryKeySelective(LzGameround record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_gameround
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    int updateByPrimaryKey(LzGameround record);
}