package com.dao;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.pojo.LzMessage;

public interface LzMessageMapper {
	
	@Select("select * from lz_message where cardid=#{cardid}")
	public LzMessage findMessByCardid(@Param("cardid") String cardid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_message
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    int deleteByPrimaryKey(Integer messageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_message
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    int insert(LzMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_message
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    int insertSelective(LzMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_message
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    LzMessage selectByPrimaryKey(Integer messageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_message
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    int updateByPrimaryKeySelective(LzMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_message
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(LzMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_message
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    int updateByPrimaryKey(LzMessage record);
}