package com.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.pojo.LzNotice;

public interface LzNoticeMapper {
	@Select("${sql}")
	public List<LzNotice> selectBySql(@Param("sql") String sql);
	
	@Select("${sql}")
	public int selectCountBySql(@Param("sql") String sql);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_notice
     *
     * @mbg.generated Mon Sep 23 19:45:33 CST 2019
     */
    int deleteByPrimaryKey(Integer noticeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_notice
     *
     * @mbg.generated Mon Sep 23 19:45:33 CST 2019
     */
    int insert(LzNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_notice
     *
     * @mbg.generated Mon Sep 23 19:45:33 CST 2019
     */
    int insertSelective(LzNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_notice
     *
     * @mbg.generated Mon Sep 23 19:45:33 CST 2019
     */
    LzNotice selectByPrimaryKey(Integer noticeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_notice
     *
     * @mbg.generated Mon Sep 23 19:45:33 CST 2019
     */
    int updateByPrimaryKeySelective(LzNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_notice
     *
     * @mbg.generated Mon Sep 23 19:45:33 CST 2019
     */
    int updateByPrimaryKey(LzNotice record);
}