package com.dao;

import com.pojo.LzRedpackagedetail;

public interface LzRedpackagedetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_redpackagedetail
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    int deleteByPrimaryKey(Integer rpdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_redpackagedetail
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    int insert(LzRedpackagedetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_redpackagedetail
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    int insertSelective(LzRedpackagedetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_redpackagedetail
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    LzRedpackagedetail selectByPrimaryKey(Integer rpdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_redpackagedetail
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    int updateByPrimaryKeySelective(LzRedpackagedetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_redpackagedetail
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    int updateByPrimaryKey(LzRedpackagedetail record);
}