package com.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.pojo.LzRedpackagedetail;

public interface LzRedpackagedetailMapper {
	@Select("${sql}")
	List<Map<String, Object>> findMapBysql(@Param("sql") String sql);
	
	@Select("${sql}")
	List<LzRedpackagedetail> findBySql(@Param("sql") String sql);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_redpackagedetail
     *
     * @mbg.generated Wed Sep 04 11:34:54 CST 2019
     */
    int deleteByPrimaryKey(Integer rpdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_redpackagedetail
     *
     * @mbg.generated Wed Sep 04 11:34:54 CST 2019
     */
    int insert(LzRedpackagedetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_redpackagedetail
     *
     * @mbg.generated Wed Sep 04 11:34:54 CST 2019
     */
    int insertSelective(LzRedpackagedetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_redpackagedetail
     *
     * @mbg.generated Wed Sep 04 11:34:54 CST 2019
     */
    LzRedpackagedetail selectByPrimaryKey(Integer rpdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_redpackagedetail
     *
     * @mbg.generated Wed Sep 04 11:34:54 CST 2019
     */
    int updateByPrimaryKeySelective(LzRedpackagedetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_redpackagedetail
     *
     * @mbg.generated Wed Sep 04 11:34:54 CST 2019
     */
    int updateByPrimaryKey(LzRedpackagedetail record);
}