package com.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.pojo.LzRedpackage;

public interface LzRedpackageMapper {
	@Select("${sql}")
	List<Map<String, Object>> findMapBysql(@Param("sql") String sql);
	
	@Select("${sql}")
	List<LzRedpackage> findBySql(@Param("sql") String sql);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_redpackage
     *
     * @mbg.generated Mon Sep 02 19:55:13 CST 2019
     */
    int deleteByPrimaryKey(Integer prid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_redpackage
     *
     * @mbg.generated Mon Sep 02 19:55:13 CST 2019
     */
    int insert(LzRedpackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_redpackage
     *
     * @mbg.generated Mon Sep 02 19:55:13 CST 2019
     */
    int insertSelective(LzRedpackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_redpackage
     *
     * @mbg.generated Mon Sep 02 19:55:13 CST 2019
     */
    LzRedpackage selectByPrimaryKey(Integer prid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_redpackage
     *
     * @mbg.generated Mon Sep 02 19:55:13 CST 2019
     */
    int updateByPrimaryKeySelective(LzRedpackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_redpackage
     *
     * @mbg.generated Mon Sep 02 19:55:13 CST 2019
     */
    int updateByPrimaryKey(LzRedpackage record);
}