package com.dao;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.pojo.LzUsergamerecord;

public interface LzUsergamerecordMapper {
	
	@Select("${sql}")
	public List<LzUsergamerecord> selectBySql(@Param("sql") String sql);
	
	@Select("select * from lz_usergamerecord where status='1' and phone=#{phone} and Createtime>ADDDATE(NOW(),INTERVAL -48 HOUR)")
	public List<LzUsergamerecord> getUncollectMoney(@Param("phone") String phone);
	
	/**
	 * 未收钱币的用户自动产生钱币
	 * @param gameid
	 * @param limit
	 */
	public void addGameRecord(@Param("gameid") int gameid,@Param("limit") BigDecimal limit);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_usergamerecord
     *
     * @mbg.generated Mon Jul 08 10:44:28 CST 2019
     */
    int deleteByPrimaryKey(Integer gamerecordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_usergamerecord
     *
     * @mbg.generated Mon Jul 08 10:44:28 CST 2019
     */
    int insert(LzUsergamerecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_usergamerecord
     *
     * @mbg.generated Mon Jul 08 10:44:28 CST 2019
     */
    int insertSelective(LzUsergamerecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_usergamerecord
     *
     * @mbg.generated Mon Jul 08 10:44:28 CST 2019
     */
    LzUsergamerecord selectByPrimaryKey(Integer gamerecordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_usergamerecord
     *
     * @mbg.generated Mon Jul 08 10:44:28 CST 2019
     */
    int updateByPrimaryKeySelective(LzUsergamerecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_usergamerecord
     *
     * @mbg.generated Mon Jul 08 10:44:28 CST 2019
     */
    int updateByPrimaryKey(LzUsergamerecord record);
}