package com.dao;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.pojo.LzUserinfo;

public interface LzUserinfoMapper {
	@Update("update lz_userinfo set balance = balance+#{money} where phone=#{phone}")
	public int dialMoneyOrder(@Param("phone")String phone,@Param("money")BigDecimal money);
	
	@Update("update lz_userinfo set weight = weight+#{weight} where phone=#{phone}")
	public int dialWeightOrder(@Param("phone")String phone,@Param("weight")BigDecimal weight);
	
	@Select("select ifnull(sum(balance),0) totalBalance,ifnull(sum(weight),0) totalWeight from lz_userinfo where status='1'")
	public Map<String, BigDecimal> getAllBalanceAndWeight();
	
	@Update("update lz_userinfo set balance=balance-#{money},weight=weight+#{weight} where phone=#{phone}")
	public void moneyToWeight(@Param("money") BigDecimal money,@Param("weight") BigDecimal weight,@Param("phone") String phone);
	
	@Select("select * from lz_userinfo where phone=#{phone} and password=#{pwd}")
	public LzUserinfo findUserbyPhoneAndPwd(@Param("phone") String phone,@Param("pwd") String pwd);
	
	@Select("select count(*) from lz_userinfo where mobileid=#{mobileId}")
	public int countByMobileId(@Param("mobileId") String mobileId);
	
	@Select("${sql}")
	public List<LzUserinfo> selectBySql(@Param("sql") String sql);
	
	@Select("${sql}")
	public int selectCountBySql(@Param("sql") String sql);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_userinfo
     *
     * @mbg.generated Wed Jul 03 14:57:14 CST 2019
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_userinfo
     *
     * @mbg.generated Wed Jul 03 14:57:14 CST 2019
     */
    int insert(LzUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_userinfo
     *
     * @mbg.generated Wed Jul 03 14:57:14 CST 2019
     */
    int insertSelective(LzUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_userinfo
     *
     * @mbg.generated Wed Jul 03 14:57:14 CST 2019
     */
    LzUserinfo selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_userinfo
     *
     * @mbg.generated Wed Jul 03 14:57:14 CST 2019
     */
    int updateByPrimaryKeySelective(LzUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_userinfo
     *
     * @mbg.generated Wed Jul 03 14:57:14 CST 2019
     */
    int updateByPrimaryKey(LzUserinfo record);
}