package com.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.pojo.LzWeightset;

public interface LzWeightsetMapper {
	@Update("update lz_weightset set status=#{status} where weiid=#{weightid}")
	public int changeWeightStatus(@Param("weightid") String weightid,@Param("status") String status);
	
	@Select("${sql}")
	public List<LzWeightset> selectBySql(@Param("sql") String sql);
	
	@Select("${sql}")
	public int selectCountBySql(@Param("sql") String sql);
	
	@Update("update lz_weightset set status='2' where status='1'")
	public int updateWeightByStatus();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_weightset
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int deleteByPrimaryKey(Integer weiid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_weightset
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int insert(LzWeightset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_weightset
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int insertSelective(LzWeightset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_weightset
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    LzWeightset selectByPrimaryKey(Integer weiid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_weightset
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int updateByPrimaryKeySelective(LzWeightset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_weightset
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    int updateByPrimaryKey(LzWeightset record);
}