package com.dao;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.pojo.LzWeightaccount;

public interface LzWeightaccountMapper {
	@Select("${sql}")
	public List<LzWeightaccount> selectBySql(@Param("sql") String sql);
	
	@Select("select sum(weight) from lz_weightaccount where phone=#{phone} and weightsetid=#{wsid}")
	BigDecimal getSumByPhoneAndWeightSetId(@Param("phone") String phone,@Param("wsid") int wsid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lz_weightaccount
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	int deleteByPrimaryKey(Integer weiaccid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lz_weightaccount
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	int insert(LzWeightaccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lz_weightaccount
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	int insertSelective(LzWeightaccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lz_weightaccount
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	LzWeightaccount selectByPrimaryKey(Integer weiaccid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lz_weightaccount
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	int updateByPrimaryKeySelective(LzWeightaccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lz_weightaccount
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	int updateByPrimaryKey(LzWeightaccount record);
}