package com.pojo;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
@JsonIgnoreProperties(value={"activeid","createtype","bindphone","usephone","createtime","usertime","status"})
public class LzActivecode {
    private Integer activeid;
    private String createtype;
    private String bindphone;
    private String usephone;
    private String activecode;
    private Date createtime;
    private Date usertime;
    private String status;
    public Integer getActiveid() {
        return activeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_activecode.Activeid
     *
     * @param activeid the value for lz_activecode.Activeid
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setActiveid(Integer activeid) {
        this.activeid = activeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_activecode.CreateType
     *
     * @return the value of lz_activecode.CreateType
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public String getCreatetype() {
        return createtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_activecode.CreateType
     *
     * @param createtype the value for lz_activecode.CreateType
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setCreatetype(String createtype) {
        this.createtype = createtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_activecode.BindPhone
     *
     * @return the value of lz_activecode.BindPhone
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public String getBindphone() {
        return bindphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_activecode.BindPhone
     *
     * @param bindphone the value for lz_activecode.BindPhone
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setBindphone(String bindphone) {
        this.bindphone = bindphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_activecode.Usephone
     *
     * @return the value of lz_activecode.Usephone
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public String getUsephone() {
        return usephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_activecode.Usephone
     *
     * @param usephone the value for lz_activecode.Usephone
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setUsephone(String usephone) {
        this.usephone = usephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_activecode.Activecode
     *
     * @return the value of lz_activecode.Activecode
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public String getActivecode() {
        return activecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_activecode.Activecode
     *
     * @param activecode the value for lz_activecode.Activecode
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setActivecode(String activecode) {
        this.activecode = activecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_activecode.Createtime
     *
     * @return the value of lz_activecode.Createtime
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_activecode.Createtime
     *
     * @param createtime the value for lz_activecode.Createtime
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_activecode.Usertime
     *
     * @return the value of lz_activecode.Usertime
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public Date getUsertime() {
        return usertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_activecode.Usertime
     *
     * @param usertime the value for lz_activecode.Usertime
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setUsertime(Date usertime) {
        this.usertime = usertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_activecode.Status
     *
     * @return the value of lz_activecode.Status
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_activecode.Status
     *
     * @param status the value for lz_activecode.Status
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }
}