package com.pojo;

import java.util.Date;

public class LzAuthcode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_authcode.codeid
     *
     * @mbg.generated Wed Jul 03 11:02:58 CST 2019
     */
    private Integer codeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_authcode.phone
     *
     * @mbg.generated Wed Jul 03 11:02:58 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_authcode.Authcode
     *
     * @mbg.generated Wed Jul 03 11:02:58 CST 2019
     */
    private String authcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_authcode.Createtime
     *
     * @mbg.generated Wed Jul 03 11:02:58 CST 2019
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_authcode.codeid
     *
     * @return the value of lz_authcode.codeid
     *
     * @mbg.generated Wed Jul 03 11:02:58 CST 2019
     */
    public Integer getCodeid() {
        return codeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_authcode.codeid
     *
     * @param codeid the value for lz_authcode.codeid
     *
     * @mbg.generated Wed Jul 03 11:02:58 CST 2019
     */
    public void setCodeid(Integer codeid) {
        this.codeid = codeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_authcode.phone
     *
     * @return the value of lz_authcode.phone
     *
     * @mbg.generated Wed Jul 03 11:02:58 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_authcode.phone
     *
     * @param phone the value for lz_authcode.phone
     *
     * @mbg.generated Wed Jul 03 11:02:58 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_authcode.Authcode
     *
     * @return the value of lz_authcode.Authcode
     *
     * @mbg.generated Wed Jul 03 11:02:58 CST 2019
     */
    public String getAuthcode() {
        return authcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_authcode.Authcode
     *
     * @param authcode the value for lz_authcode.Authcode
     *
     * @mbg.generated Wed Jul 03 11:02:58 CST 2019
     */
    public void setAuthcode(String authcode) {
        this.authcode = authcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_authcode.Createtime
     *
     * @return the value of lz_authcode.Createtime
     *
     * @mbg.generated Wed Jul 03 11:02:58 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_authcode.Createtime
     *
     * @param createtime the value for lz_authcode.Createtime
     *
     * @mbg.generated Wed Jul 03 11:02:58 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}