package com.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class LzDayaccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dayaccount.dayid
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private Integer dayid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dayaccount.Totalbalance
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private BigDecimal totalbalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dayaccount.totalEnter
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private BigDecimal totalenter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dayaccount.TotalOut
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private BigDecimal totalout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dayaccount.Daytime
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private Date daytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dayaccount.Dealtime
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private Date dealtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dayaccount.dayid
     *
     * @return the value of lz_dayaccount.dayid
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public Integer getDayid() {
        return dayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dayaccount.dayid
     *
     * @param dayid the value for lz_dayaccount.dayid
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setDayid(Integer dayid) {
        this.dayid = dayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dayaccount.Totalbalance
     *
     * @return the value of lz_dayaccount.Totalbalance
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public BigDecimal getTotalbalance() {
        return totalbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dayaccount.Totalbalance
     *
     * @param totalbalance the value for lz_dayaccount.Totalbalance
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setTotalbalance(BigDecimal totalbalance) {
        this.totalbalance = totalbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dayaccount.totalEnter
     *
     * @return the value of lz_dayaccount.totalEnter
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public BigDecimal getTotalenter() {
        return totalenter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dayaccount.totalEnter
     *
     * @param totalenter the value for lz_dayaccount.totalEnter
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setTotalenter(BigDecimal totalenter) {
        this.totalenter = totalenter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dayaccount.TotalOut
     *
     * @return the value of lz_dayaccount.TotalOut
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public BigDecimal getTotalout() {
        return totalout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dayaccount.TotalOut
     *
     * @param totalout the value for lz_dayaccount.TotalOut
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setTotalout(BigDecimal totalout) {
        this.totalout = totalout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dayaccount.Daytime
     *
     * @return the value of lz_dayaccount.Daytime
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public Date getDaytime() {
        return daytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dayaccount.Daytime
     *
     * @param daytime the value for lz_dayaccount.Daytime
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setDaytime(Date daytime) {
        this.daytime = daytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dayaccount.Dealtime
     *
     * @return the value of lz_dayaccount.Dealtime
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public Date getDealtime() {
        return dealtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dayaccount.Dealtime
     *
     * @param dealtime the value for lz_dayaccount.Dealtime
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setDealtime(Date dealtime) {
        this.dealtime = dealtime;
    }
}