package com.pojo;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
@JsonIgnoreProperties(value={"dealid","gameid","status","dealtime"})
public class LzDealorder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dealorder.Dealid
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private Integer dealid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dealorder.Dealtype
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private String dealtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dealorder.Gameid
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private Integer gameid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dealorder.Dealamount
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private BigDecimal dealamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dealorder.Dealtime
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private Date dealtime;
    private String showDealTime;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dealorder.Dealphone
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private String dealphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dealorder.Status
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dealorder.Dealid
     *
     * @return the value of lz_dealorder.Dealid
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public Integer getDealid() {
        return dealid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dealorder.Dealid
     *
     * @param dealid the value for lz_dealorder.Dealid
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setDealid(Integer dealid) {
        this.dealid = dealid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dealorder.Dealtype
     *
     * @return the value of lz_dealorder.Dealtype
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public String getDealtype() {
        return dealtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dealorder.Dealtype
     *
     * @param dealtype the value for lz_dealorder.Dealtype
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setDealtype(String dealtype) {
        this.dealtype = dealtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dealorder.Gameid
     *
     * @return the value of lz_dealorder.Gameid
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public Integer getGameid() {
        return gameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dealorder.Gameid
     *
     * @param gameid the value for lz_dealorder.Gameid
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setGameid(Integer gameid) {
        this.gameid = gameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dealorder.Dealamount
     *
     * @return the value of lz_dealorder.Dealamount
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public BigDecimal getDealamount() {
        return dealamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dealorder.Dealamount
     *
     * @param dealamount the value for lz_dealorder.Dealamount
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setDealamount(BigDecimal dealamount) {
        this.dealamount = dealamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dealorder.Dealtime
     *
     * @return the value of lz_dealorder.Dealtime
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public Date getDealtime() {
        return dealtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dealorder.Dealtime
     *
     * @param dealtime the value for lz_dealorder.Dealtime
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setDealtime(Date dealtime) {
        this.dealtime = dealtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dealorder.Dealphone
     *
     * @return the value of lz_dealorder.Dealphone
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public String getDealphone() {
        return dealphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dealorder.Dealphone
     *
     * @param dealphone the value for lz_dealorder.Dealphone
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setDealphone(String dealphone) {
        this.dealphone = dealphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dealorder.Status
     *
     * @return the value of lz_dealorder.Status
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dealorder.Status
     *
     * @param status the value for lz_dealorder.Status
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

	public String getShowDealTime() {
		if(dealtime!=null){
			SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd hh:mm:ss");
			return sdf.format(dealtime);
		}else{
			return "";
		}
		
	}

	public void setShowDealTime(String showDealTime) {
		this.showDealTime = showDealTime;
	}
    
}