package com.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class LzDialset {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dialset.Dialid
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private Integer dialid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dialset.Content1
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private String content1;
    private BigDecimal count1;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dialset.Odds1
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private BigDecimal odds1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dialset.Content2
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private String content2;
    private BigDecimal count2;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dialset.Odds2
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private BigDecimal odds2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dialset.Content3
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private String content3;
    private BigDecimal count3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dialset.Odds3
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private BigDecimal odds3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dialset.Content4
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private String content4;
    private BigDecimal count4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dialset.Odds4
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private BigDecimal odds4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dialset.Content5
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private String content5;
    private BigDecimal count5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dialset.Odds5
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private BigDecimal odds5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dialset.Content6
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private String content6;
    private BigDecimal count6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dialset.Odds6
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private BigDecimal odds6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dialset.Createtime
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_dialset.Status
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private String status;
    
    public BigDecimal getCount1() {
		return count1;
	}

	public void setCount1(BigDecimal count1) {
		this.count1 = count1;
	}

	public BigDecimal getCount2() {
		return count2;
	}

	public void setCount2(BigDecimal count2) {
		this.count2 = count2;
	}

	public BigDecimal getCount3() {
		return count3;
	}

	public void setCount3(BigDecimal count3) {
		this.count3 = count3;
	}

	public BigDecimal getCount4() {
		return count4;
	}

	public void setCount4(BigDecimal count4) {
		this.count4 = count4;
	}

	public BigDecimal getCount5() {
		return count5;
	}

	public void setCount5(BigDecimal count5) {
		this.count5 = count5;
	}

	public BigDecimal getCount6() {
		return count6;
	}

	public void setCount6(BigDecimal count6) {
		this.count6 = count6;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dialset.Dialid
     *
     * @return the value of lz_dialset.Dialid
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public Integer getDialid() {
        return dialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dialset.Dialid
     *
     * @param dialid the value for lz_dialset.Dialid
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setDialid(Integer dialid) {
        this.dialid = dialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dialset.Content1
     *
     * @return the value of lz_dialset.Content1
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public String getContent1() {
        return content1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dialset.Content1
     *
     * @param content1 the value for lz_dialset.Content1
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setContent1(String content1) {
        this.content1 = content1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dialset.Odds1
     *
     * @return the value of lz_dialset.Odds1
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public BigDecimal getOdds1() {
        return odds1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dialset.Odds1
     *
     * @param odds1 the value for lz_dialset.Odds1
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setOdds1(BigDecimal odds1) {
        this.odds1 = odds1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dialset.Content2
     *
     * @return the value of lz_dialset.Content2
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public String getContent2() {
        return content2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dialset.Content2
     *
     * @param content2 the value for lz_dialset.Content2
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setContent2(String content2) {
        this.content2 = content2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dialset.Odds2
     *
     * @return the value of lz_dialset.Odds2
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public BigDecimal getOdds2() {
        return odds2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dialset.Odds2
     *
     * @param odds2 the value for lz_dialset.Odds2
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setOdds2(BigDecimal odds2) {
        this.odds2 = odds2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dialset.Content3
     *
     * @return the value of lz_dialset.Content3
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public String getContent3() {
        return content3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dialset.Content3
     *
     * @param content3 the value for lz_dialset.Content3
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setContent3(String content3) {
        this.content3 = content3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dialset.Odds3
     *
     * @return the value of lz_dialset.Odds3
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public BigDecimal getOdds3() {
        return odds3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dialset.Odds3
     *
     * @param odds3 the value for lz_dialset.Odds3
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setOdds3(BigDecimal odds3) {
        this.odds3 = odds3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dialset.Content4
     *
     * @return the value of lz_dialset.Content4
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public String getContent4() {
        return content4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dialset.Content4
     *
     * @param content4 the value for lz_dialset.Content4
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setContent4(String content4) {
        this.content4 = content4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dialset.Odds4
     *
     * @return the value of lz_dialset.Odds4
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public BigDecimal getOdds4() {
        return odds4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dialset.Odds4
     *
     * @param odds4 the value for lz_dialset.Odds4
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setOdds4(BigDecimal odds4) {
        this.odds4 = odds4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dialset.Content5
     *
     * @return the value of lz_dialset.Content5
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public String getContent5() {
        return content5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dialset.Content5
     *
     * @param content5 the value for lz_dialset.Content5
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setContent5(String content5) {
        this.content5 = content5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dialset.Odds5
     *
     * @return the value of lz_dialset.Odds5
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public BigDecimal getOdds5() {
        return odds5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dialset.Odds5
     *
     * @param odds5 the value for lz_dialset.Odds5
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setOdds5(BigDecimal odds5) {
        this.odds5 = odds5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dialset.Content6
     *
     * @return the value of lz_dialset.Content6
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public String getContent6() {
        return content6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dialset.Content6
     *
     * @param content6 the value for lz_dialset.Content6
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setContent6(String content6) {
        this.content6 = content6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dialset.Odds6
     *
     * @return the value of lz_dialset.Odds6
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public BigDecimal getOdds6() {
        return odds6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dialset.Odds6
     *
     * @param odds6 the value for lz_dialset.Odds6
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setOdds6(BigDecimal odds6) {
        this.odds6 = odds6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dialset.Createtime
     *
     * @return the value of lz_dialset.Createtime
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dialset.Createtime
     *
     * @param createtime the value for lz_dialset.Createtime
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_dialset.Status
     *
     * @return the value of lz_dialset.Status
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_dialset.Status
     *
     * @param status the value for lz_dialset.Status
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }
}