package com.pojo;

public class LzFriendlist {
    private Integer flid;
    private String userphone;
    private String friendphone;
    private String friendusercode;
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_friendlist.flid
     *
     * @return the value of lz_friendlist.flid
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public Integer getFlid() {
        return flid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_friendlist.flid
     *
     * @param flid the value for lz_friendlist.flid
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public void setFlid(Integer flid) {
        this.flid = flid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_friendlist.userphone
     *
     * @return the value of lz_friendlist.userphone
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public String getUserphone() {
        return userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_friendlist.userphone
     *
     * @param userphone the value for lz_friendlist.userphone
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public void setUserphone(String userphone) {
        this.userphone = userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_friendlist.friendphone
     *
     * @return the value of lz_friendlist.friendphone
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public String getFriendphone() {
        return friendphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_friendlist.friendphone
     *
     * @param friendphone the value for lz_friendlist.friendphone
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public void setFriendphone(String friendphone) {
        this.friendphone = friendphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_friendlist.friendusercode
     *
     * @return the value of lz_friendlist.friendusercode
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public String getFriendusercode() {
        return friendusercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_friendlist.friendusercode
     *
     * @param friendusercode the value for lz_friendlist.friendusercode
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public void setFriendusercode(String friendusercode) {
        this.friendusercode = friendusercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_friendlist.status
     *
     * @return the value of lz_friendlist.status
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_friendlist.status
     *
     * @param status the value for lz_friendlist.status
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }
}