package com.pojo;

import java.util.Date;

public class LzFriendapply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_friendapply.faid
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    private Integer faid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_friendapply.userphone
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    private String userphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_friendapply.usercode
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    private String usercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_friendapply.friendphone
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    private String friendphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_friendapply.friendusercode
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    private String friendusercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_friendapply.applytime
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    private Date applytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_friendapply.status
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_friendapply.faid
     *
     * @return the value of lz_friendapply.faid
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public Integer getFaid() {
        return faid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_friendapply.faid
     *
     * @param faid the value for lz_friendapply.faid
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public void setFaid(Integer faid) {
        this.faid = faid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_friendapply.userphone
     *
     * @return the value of lz_friendapply.userphone
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public String getUserphone() {
        return userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_friendapply.userphone
     *
     * @param userphone the value for lz_friendapply.userphone
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public void setUserphone(String userphone) {
        this.userphone = userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_friendapply.usercode
     *
     * @return the value of lz_friendapply.usercode
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_friendapply.usercode
     *
     * @param usercode the value for lz_friendapply.usercode
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_friendapply.friendphone
     *
     * @return the value of lz_friendapply.friendphone
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public String getFriendphone() {
        return friendphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_friendapply.friendphone
     *
     * @param friendphone the value for lz_friendapply.friendphone
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public void setFriendphone(String friendphone) {
        this.friendphone = friendphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_friendapply.friendusercode
     *
     * @return the value of lz_friendapply.friendusercode
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public String getFriendusercode() {
        return friendusercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_friendapply.friendusercode
     *
     * @param friendusercode the value for lz_friendapply.friendusercode
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public void setFriendusercode(String friendusercode) {
        this.friendusercode = friendusercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_friendapply.applytime
     *
     * @return the value of lz_friendapply.applytime
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public Date getApplytime() {
        return applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_friendapply.applytime
     *
     * @param applytime the value for lz_friendapply.applytime
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public void setApplytime(Date applytime) {
        this.applytime = applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_friendapply.status
     *
     * @return the value of lz_friendapply.status
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_friendapply.status
     *
     * @param status the value for lz_friendapply.status
     *
     * @mbg.generated Fri Aug 30 16:54:17 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }
}