package com.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class LzGameround {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_gameround.Gameid
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    private Integer gameid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_gameround.PTotal
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    private BigDecimal ptotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_gameround.RTotal
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    private BigDecimal rtotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_gameround.WeiTotal
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    private BigDecimal weitotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_gameround.BalTotal
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    private BigDecimal baltotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_gameround.Createtime
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_gameround.Status
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_gameround.Gameid
     *
     * @return the value of lz_gameround.Gameid
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    public Integer getGameid() {
        return gameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_gameround.Gameid
     *
     * @param gameid the value for lz_gameround.Gameid
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    public void setGameid(Integer gameid) {
        this.gameid = gameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_gameround.PTotal
     *
     * @return the value of lz_gameround.PTotal
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    public BigDecimal getPtotal() {
        return ptotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_gameround.PTotal
     *
     * @param ptotal the value for lz_gameround.PTotal
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    public void setPtotal(BigDecimal ptotal) {
        this.ptotal = ptotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_gameround.RTotal
     *
     * @return the value of lz_gameround.RTotal
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    public BigDecimal getRtotal() {
        return rtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_gameround.RTotal
     *
     * @param rtotal the value for lz_gameround.RTotal
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    public void setRtotal(BigDecimal rtotal) {
        this.rtotal = rtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_gameround.WeiTotal
     *
     * @return the value of lz_gameround.WeiTotal
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    public BigDecimal getWeitotal() {
        return weitotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_gameround.WeiTotal
     *
     * @param weitotal the value for lz_gameround.WeiTotal
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    public void setWeitotal(BigDecimal weitotal) {
        this.weitotal = weitotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_gameround.BalTotal
     *
     * @return the value of lz_gameround.BalTotal
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    public BigDecimal getBaltotal() {
        return baltotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_gameround.BalTotal
     *
     * @param baltotal the value for lz_gameround.BalTotal
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    public void setBaltotal(BigDecimal baltotal) {
        this.baltotal = baltotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_gameround.Createtime
     *
     * @return the value of lz_gameround.Createtime
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_gameround.Createtime
     *
     * @param createtime the value for lz_gameround.Createtime
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_gameround.Status
     *
     * @return the value of lz_gameround.Status
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_gameround.Status
     *
     * @param status the value for lz_gameround.Status
     *
     * @mbg.generated Wed Jun 26 14:20:49 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }
}