package com.pojo;

public class LzManager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_manager.managerid
     *
     * @mbg.generated Tue Jun 25 20:11:01 CST 2019
     */
    private Integer managerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_manager.managername
     *
     * @mbg.generated Tue Jun 25 20:11:01 CST 2019
     */
    private String managername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_manager.managerpwd
     *
     * @mbg.generated Tue Jun 25 20:11:01 CST 2019
     */
    private String managerpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_manager.managertype
     *
     * @mbg.generated Tue Jun 25 20:11:01 CST 2019
     */
    private String managertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_manager.status
     *
     * @mbg.generated Tue Jun 25 20:11:01 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_manager.managerid
     *
     * @return the value of lz_manager.managerid
     *
     * @mbg.generated Tue Jun 25 20:11:01 CST 2019
     */
    public Integer getManagerid() {
        return managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_manager.managerid
     *
     * @param managerid the value for lz_manager.managerid
     *
     * @mbg.generated Tue Jun 25 20:11:01 CST 2019
     */
    public void setManagerid(Integer managerid) {
        this.managerid = managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_manager.managername
     *
     * @return the value of lz_manager.managername
     *
     * @mbg.generated Tue Jun 25 20:11:01 CST 2019
     */
    public String getManagername() {
        return managername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_manager.managername
     *
     * @param managername the value for lz_manager.managername
     *
     * @mbg.generated Tue Jun 25 20:11:01 CST 2019
     */
    public void setManagername(String managername) {
        this.managername = managername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_manager.managerpwd
     *
     * @return the value of lz_manager.managerpwd
     *
     * @mbg.generated Tue Jun 25 20:11:01 CST 2019
     */
    public String getManagerpwd() {
        return managerpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_manager.managerpwd
     *
     * @param managerpwd the value for lz_manager.managerpwd
     *
     * @mbg.generated Tue Jun 25 20:11:01 CST 2019
     */
    public void setManagerpwd(String managerpwd) {
        this.managerpwd = managerpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_manager.managertype
     *
     * @return the value of lz_manager.managertype
     *
     * @mbg.generated Tue Jun 25 20:11:01 CST 2019
     */
    public String getManagertype() {
        return managertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_manager.managertype
     *
     * @param managertype the value for lz_manager.managertype
     *
     * @mbg.generated Tue Jun 25 20:11:01 CST 2019
     */
    public void setManagertype(String managertype) {
        this.managertype = managertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_manager.status
     *
     * @return the value of lz_manager.status
     *
     * @mbg.generated Tue Jun 25 20:11:01 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_manager.status
     *
     * @param status the value for lz_manager.status
     *
     * @mbg.generated Tue Jun 25 20:11:01 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }
}