package com.pojo;

import java.util.Date;

public class LzMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_message.messageid
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    private Integer messageid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_message.messType
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    private String messtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_message.Messtitle
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    private String messtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_message.Createtime
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_message.cardid
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    private String cardid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_message.Status
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_message.Messcontext
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    private String messcontext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_message.messageid
     *
     * @return the value of lz_message.messageid
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    public Integer getMessageid() {
        return messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_message.messageid
     *
     * @param messageid the value for lz_message.messageid
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    public void setMessageid(Integer messageid) {
        this.messageid = messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_message.messType
     *
     * @return the value of lz_message.messType
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    public String getMesstype() {
        return messtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_message.messType
     *
     * @param messtype the value for lz_message.messType
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    public void setMesstype(String messtype) {
        this.messtype = messtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_message.Messtitle
     *
     * @return the value of lz_message.Messtitle
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    public String getMesstitle() {
        return messtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_message.Messtitle
     *
     * @param messtitle the value for lz_message.Messtitle
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    public void setMesstitle(String messtitle) {
        this.messtitle = messtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_message.Createtime
     *
     * @return the value of lz_message.Createtime
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_message.Createtime
     *
     * @param createtime the value for lz_message.Createtime
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_message.cardid
     *
     * @return the value of lz_message.cardid
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    public String getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_message.cardid
     *
     * @param cardid the value for lz_message.cardid
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    public void setCardid(String cardid) {
        this.cardid = cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_message.Status
     *
     * @return the value of lz_message.Status
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_message.Status
     *
     * @param status the value for lz_message.Status
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_message.Messcontext
     *
     * @return the value of lz_message.Messcontext
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    public String getMesscontext() {
        return messcontext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_message.Messcontext
     *
     * @param messcontext the value for lz_message.Messcontext
     *
     * @mbg.generated Fri Jun 28 14:42:04 CST 2019
     */
    public void setMesscontext(String messcontext) {
        this.messcontext = messcontext;
    }
}