package com.pojo;

import java.text.SimpleDateFormat;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
@JsonIgnoreProperties({"noticeid","createtime","status"})
public class LzNotice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_notice.noticeid
     *
     * @mbg.generated Mon Sep 23 19:45:33 CST 2019
     */
    private Integer noticeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_notice.title
     *
     * @mbg.generated Mon Sep 23 19:45:33 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_notice.content
     *
     * @mbg.generated Mon Sep 23 19:45:33 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_notice.createtime
     *
     * @mbg.generated Mon Sep 23 19:45:33 CST 2019
     */
    private Date createtime;
    String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_notice.status
     *
     * @mbg.generated Mon Sep 23 19:45:33 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_notice.noticeid
     *
     * @return the value of lz_notice.noticeid
     *
     * @mbg.generated Mon Sep 23 19:45:33 CST 2019
     */
    public Integer getNoticeid() {
        return noticeid;
    }

    public String getTime() {
    	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
		return sdf.format(createtime);
	}

	public void setTime(String time) {
		this.time = time;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_notice.noticeid
     *
     * @param noticeid the value for lz_notice.noticeid
     *
     * @mbg.generated Mon Sep 23 19:45:33 CST 2019
     */
    public void setNoticeid(Integer noticeid) {
        this.noticeid = noticeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_notice.title
     *
     * @return the value of lz_notice.title
     *
     * @mbg.generated Mon Sep 23 19:45:33 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_notice.title
     *
     * @param title the value for lz_notice.title
     *
     * @mbg.generated Mon Sep 23 19:45:33 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_notice.content
     *
     * @return the value of lz_notice.content
     *
     * @mbg.generated Mon Sep 23 19:45:33 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_notice.content
     *
     * @param content the value for lz_notice.content
     *
     * @mbg.generated Mon Sep 23 19:45:33 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_notice.createtime
     *
     * @return the value of lz_notice.createtime
     *
     * @mbg.generated Mon Sep 23 19:45:33 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_notice.createtime
     *
     * @param createtime the value for lz_notice.createtime
     *
     * @mbg.generated Mon Sep 23 19:45:33 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_notice.status
     *
     * @return the value of lz_notice.status
     *
     * @mbg.generated Mon Sep 23 19:45:33 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_notice.status
     *
     * @param status the value for lz_notice.status
     *
     * @mbg.generated Mon Sep 23 19:45:33 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }
}