package com.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class LzRedpackagedetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_redpackagedetail.rpdid
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    private Integer rpdid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_redpackagedetail.rpid
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    private Integer rpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_redpackagedetail.receivephone
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    private String receivephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_redpackagedetail.amount
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_redpackagedetail.receivetime
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    private Date receivetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_redpackagedetail.status
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_redpackagedetail.rpdid
     *
     * @return the value of lz_redpackagedetail.rpdid
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public Integer getRpdid() {
        return rpdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_redpackagedetail.rpdid
     *
     * @param rpdid the value for lz_redpackagedetail.rpdid
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public void setRpdid(Integer rpdid) {
        this.rpdid = rpdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_redpackagedetail.rpid
     *
     * @return the value of lz_redpackagedetail.rpid
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public Integer getRpid() {
        return rpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_redpackagedetail.rpid
     *
     * @param rpid the value for lz_redpackagedetail.rpid
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public void setRpid(Integer rpid) {
        this.rpid = rpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_redpackagedetail.receivephone
     *
     * @return the value of lz_redpackagedetail.receivephone
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public String getReceivephone() {
        return receivephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_redpackagedetail.receivephone
     *
     * @param receivephone the value for lz_redpackagedetail.receivephone
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public void setReceivephone(String receivephone) {
        this.receivephone = receivephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_redpackagedetail.amount
     *
     * @return the value of lz_redpackagedetail.amount
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_redpackagedetail.amount
     *
     * @param amount the value for lz_redpackagedetail.amount
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_redpackagedetail.receivetime
     *
     * @return the value of lz_redpackagedetail.receivetime
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public Date getReceivetime() {
        return receivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_redpackagedetail.receivetime
     *
     * @param receivetime the value for lz_redpackagedetail.receivetime
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public void setReceivetime(Date receivetime) {
        this.receivetime = receivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_redpackagedetail.status
     *
     * @return the value of lz_redpackagedetail.status
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_redpackagedetail.status
     *
     * @param status the value for lz_redpackagedetail.status
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }
}