package com.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class LzRedpackage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_redpackage.prid
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    private Integer prid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_redpackage.sendid
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    private Integer sendid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_redpackage.type
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_redpackage.amount
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_redpackage.count
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_redpackage.sendtime
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    private Date sendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_redpackage.status
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_redpackage.prid
     *
     * @return the value of lz_redpackage.prid
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public Integer getPrid() {
        return prid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_redpackage.prid
     *
     * @param prid the value for lz_redpackage.prid
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public void setPrid(Integer prid) {
        this.prid = prid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_redpackage.sendid
     *
     * @return the value of lz_redpackage.sendid
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public Integer getSendid() {
        return sendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_redpackage.sendid
     *
     * @param sendid the value for lz_redpackage.sendid
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public void setSendid(Integer sendid) {
        this.sendid = sendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_redpackage.type
     *
     * @return the value of lz_redpackage.type
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_redpackage.type
     *
     * @param type the value for lz_redpackage.type
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_redpackage.amount
     *
     * @return the value of lz_redpackage.amount
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_redpackage.amount
     *
     * @param amount the value for lz_redpackage.amount
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_redpackage.count
     *
     * @return the value of lz_redpackage.count
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_redpackage.count
     *
     * @param count the value for lz_redpackage.count
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_redpackage.sendtime
     *
     * @return the value of lz_redpackage.sendtime
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_redpackage.sendtime
     *
     * @param sendtime the value for lz_redpackage.sendtime
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_redpackage.status
     *
     * @return the value of lz_redpackage.status
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_redpackage.status
     *
     * @param status the value for lz_redpackage.status
     *
     * @mbg.generated Mon Sep 02 19:18:29 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }
}