package com.pojo;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
@JsonIgnoreProperties({"rpdid","rpid","receivetime","status"})
public class LzRedpackagedetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lz_redpackagedetail.rpdid
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	private Integer rpdid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lz_redpackagedetail.rpid
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	private Integer rpid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lz_redpackagedetail.receivephone
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	private String receivephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lz_redpackagedetail.receiveUsercode
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	private String receiveusercode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lz_redpackagedetail.recevieNikeName
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	private String recevienikename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lz_redpackagedetail.picpath
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	private String picpath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lz_redpackagedetail.amount
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	private BigDecimal amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lz_redpackagedetail.receivetime
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	private Date receivetime;
	
	String dealtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lz_redpackagedetail.status
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	private String status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lz_redpackagedetail.rpdid
	 * @return  the value of lz_redpackagedetail.rpdid
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	public Integer getRpdid() {
		return rpdid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lz_redpackagedetail.rpdid
	 * @param rpdid  the value for lz_redpackagedetail.rpdid
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	public void setRpdid(Integer rpdid) {
		this.rpdid = rpdid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lz_redpackagedetail.rpid
	 * @return  the value of lz_redpackagedetail.rpid
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	public Integer getRpid() {
		return rpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lz_redpackagedetail.rpid
	 * @param rpid  the value for lz_redpackagedetail.rpid
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	public void setRpid(Integer rpid) {
		this.rpid = rpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lz_redpackagedetail.receivephone
	 * @return  the value of lz_redpackagedetail.receivephone
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	public String getReceivephone() {
		return receivephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lz_redpackagedetail.receivephone
	 * @param receivephone  the value for lz_redpackagedetail.receivephone
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	public void setReceivephone(String receivephone) {
		this.receivephone = receivephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lz_redpackagedetail.receiveUsercode
	 * @return  the value of lz_redpackagedetail.receiveUsercode
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	public String getReceiveusercode() {
		return receiveusercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lz_redpackagedetail.receiveUsercode
	 * @param receiveusercode  the value for lz_redpackagedetail.receiveUsercode
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	public void setReceiveusercode(String receiveusercode) {
		this.receiveusercode = receiveusercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lz_redpackagedetail.recevieNikeName
	 * @return  the value of lz_redpackagedetail.recevieNikeName
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	public String getRecevienikename() {
		return recevienikename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lz_redpackagedetail.recevieNikeName
	 * @param recevienikename  the value for lz_redpackagedetail.recevieNikeName
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	public void setRecevienikename(String recevienikename) {
		this.recevienikename = recevienikename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lz_redpackagedetail.picpath
	 * @return  the value of lz_redpackagedetail.picpath
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	public String getPicpath() {
		return picpath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lz_redpackagedetail.picpath
	 * @param picpath  the value for lz_redpackagedetail.picpath
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	public void setPicpath(String picpath) {
		this.picpath = picpath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lz_redpackagedetail.amount
	 * @return  the value of lz_redpackagedetail.amount
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	public BigDecimal getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lz_redpackagedetail.amount
	 * @param amount  the value for lz_redpackagedetail.amount
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lz_redpackagedetail.receivetime
	 * @return  the value of lz_redpackagedetail.receivetime
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	public Date getReceivetime() {
		return receivetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lz_redpackagedetail.receivetime
	 * @param receivetime  the value for lz_redpackagedetail.receivetime
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	public void setReceivetime(Date receivetime) {
		this.receivetime = receivetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lz_redpackagedetail.status
	 * @return  the value of lz_redpackagedetail.status
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lz_redpackagedetail.status
	 * @param status  the value for lz_redpackagedetail.status
	 * @mbg.generated  Sun Sep 08 15:14:55 CST 2019
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	public String getDealtime() {
		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
		return sdf.format(receivetime);
	}

	public void setDealtime(String dealtime) {
		this.dealtime = dealtime;
	}
	
}