package com.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class LzUserinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_userinfo.Userid
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_userinfo.usercode
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    private String usercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_userinfo.nickName
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_userinfo.Phone
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_userinfo.Idcard
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_userinfo.Password
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_userinfo.Weight
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    private BigDecimal weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_userinfo.InviteNum
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    private Integer invitenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_userinfo.Balance
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    private BigDecimal balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_userinfo.Createtime
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_userinfo.InvitePhone
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    private String invitephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_userinfo.AwardNum
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    private Integer awardnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_userinfo.mobileid
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    private String mobileid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_userinfo.picpath
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    private String picpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_userinfo.status
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_userinfo.Userid
     *
     * @return the value of lz_userinfo.Userid
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_userinfo.Userid
     *
     * @param userid the value for lz_userinfo.Userid
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_userinfo.usercode
     *
     * @return the value of lz_userinfo.usercode
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_userinfo.usercode
     *
     * @param usercode the value for lz_userinfo.usercode
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_userinfo.nickName
     *
     * @return the value of lz_userinfo.nickName
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_userinfo.nickName
     *
     * @param nickname the value for lz_userinfo.nickName
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_userinfo.Phone
     *
     * @return the value of lz_userinfo.Phone
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_userinfo.Phone
     *
     * @param phone the value for lz_userinfo.Phone
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_userinfo.Idcard
     *
     * @return the value of lz_userinfo.Idcard
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_userinfo.Idcard
     *
     * @param idcard the value for lz_userinfo.Idcard
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_userinfo.Password
     *
     * @return the value of lz_userinfo.Password
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_userinfo.Password
     *
     * @param password the value for lz_userinfo.Password
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_userinfo.Weight
     *
     * @return the value of lz_userinfo.Weight
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_userinfo.Weight
     *
     * @param weight the value for lz_userinfo.Weight
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_userinfo.InviteNum
     *
     * @return the value of lz_userinfo.InviteNum
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public Integer getInvitenum() {
        return invitenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_userinfo.InviteNum
     *
     * @param invitenum the value for lz_userinfo.InviteNum
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public void setInvitenum(Integer invitenum) {
        this.invitenum = invitenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_userinfo.Balance
     *
     * @return the value of lz_userinfo.Balance
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_userinfo.Balance
     *
     * @param balance the value for lz_userinfo.Balance
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_userinfo.Createtime
     *
     * @return the value of lz_userinfo.Createtime
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_userinfo.Createtime
     *
     * @param createtime the value for lz_userinfo.Createtime
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_userinfo.InvitePhone
     *
     * @return the value of lz_userinfo.InvitePhone
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public String getInvitephone() {
        return invitephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_userinfo.InvitePhone
     *
     * @param invitephone the value for lz_userinfo.InvitePhone
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public void setInvitephone(String invitephone) {
        this.invitephone = invitephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_userinfo.AwardNum
     *
     * @return the value of lz_userinfo.AwardNum
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public Integer getAwardnum() {
        return awardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_userinfo.AwardNum
     *
     * @param awardnum the value for lz_userinfo.AwardNum
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public void setAwardnum(Integer awardnum) {
        this.awardnum = awardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_userinfo.mobileid
     *
     * @return the value of lz_userinfo.mobileid
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public String getMobileid() {
        return mobileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_userinfo.mobileid
     *
     * @param mobileid the value for lz_userinfo.mobileid
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public void setMobileid(String mobileid) {
        this.mobileid = mobileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_userinfo.picpath
     *
     * @return the value of lz_userinfo.picpath
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public String getPicpath() {
        return picpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_userinfo.picpath
     *
     * @param picpath the value for lz_userinfo.picpath
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public void setPicpath(String picpath) {
        this.picpath = picpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_userinfo.status
     *
     * @return the value of lz_userinfo.status
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_userinfo.status
     *
     * @param status the value for lz_userinfo.status
     *
     * @mbg.generated Thu Sep 05 08:46:07 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }
}