package com.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class LzUsergamerecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lz_usergamerecord.GameRecordid
	 * @mbg.generated  Mon Jul 08 10:44:28 CST 2019
	 */
	private Integer gamerecordid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lz_usergamerecord.Gameid
	 * @mbg.generated  Mon Jul 08 10:44:28 CST 2019
	 */
	private Integer gameid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lz_usergamerecord.Phone
	 * @mbg.generated  Mon Jul 08 10:44:28 CST 2019
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lz_usergamerecord.weight
	 * @mbg.generated  Mon Jul 08 10:44:28 CST 2019
	 */
	private BigDecimal weight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lz_usergamerecord.receivable
	 * @mbg.generated  Mon Jul 08 10:44:28 CST 2019
	 */
	private BigDecimal receivable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lz_usergamerecord.Createtime
	 * @mbg.generated  Mon Jul 08 10:44:28 CST 2019
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lz_usergamerecord.Status
	 * @mbg.generated  Mon Jul 08 10:44:28 CST 2019
	 */
	private String status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lz_usergamerecord.GameRecordid
	 * @return  the value of lz_usergamerecord.GameRecordid
	 * @mbg.generated  Mon Jul 08 10:44:28 CST 2019
	 */
	public Integer getGamerecordid() {
		return gamerecordid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lz_usergamerecord.GameRecordid
	 * @param gamerecordid  the value for lz_usergamerecord.GameRecordid
	 * @mbg.generated  Mon Jul 08 10:44:28 CST 2019
	 */
	public void setGamerecordid(Integer gamerecordid) {
		this.gamerecordid = gamerecordid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lz_usergamerecord.Gameid
	 * @return  the value of lz_usergamerecord.Gameid
	 * @mbg.generated  Mon Jul 08 10:44:28 CST 2019
	 */
	public Integer getGameid() {
		return gameid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lz_usergamerecord.Gameid
	 * @param gameid  the value for lz_usergamerecord.Gameid
	 * @mbg.generated  Mon Jul 08 10:44:28 CST 2019
	 */
	public void setGameid(Integer gameid) {
		this.gameid = gameid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lz_usergamerecord.Phone
	 * @return  the value of lz_usergamerecord.Phone
	 * @mbg.generated  Mon Jul 08 10:44:28 CST 2019
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lz_usergamerecord.Phone
	 * @param phone  the value for lz_usergamerecord.Phone
	 * @mbg.generated  Mon Jul 08 10:44:28 CST 2019
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lz_usergamerecord.weight
	 * @return  the value of lz_usergamerecord.weight
	 * @mbg.generated  Mon Jul 08 10:44:28 CST 2019
	 */
	public BigDecimal getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lz_usergamerecord.weight
	 * @param weight  the value for lz_usergamerecord.weight
	 * @mbg.generated  Mon Jul 08 10:44:28 CST 2019
	 */
	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lz_usergamerecord.receivable
	 * @return  the value of lz_usergamerecord.receivable
	 * @mbg.generated  Mon Jul 08 10:44:28 CST 2019
	 */
	public BigDecimal getReceivable() {
		return receivable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lz_usergamerecord.receivable
	 * @param receivable  the value for lz_usergamerecord.receivable
	 * @mbg.generated  Mon Jul 08 10:44:28 CST 2019
	 */
	public void setReceivable(BigDecimal receivable) {
		this.receivable = receivable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lz_usergamerecord.Createtime
	 * @return  the value of lz_usergamerecord.Createtime
	 * @mbg.generated  Mon Jul 08 10:44:28 CST 2019
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lz_usergamerecord.Createtime
	 * @param createtime  the value for lz_usergamerecord.Createtime
	 * @mbg.generated  Mon Jul 08 10:44:28 CST 2019
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lz_usergamerecord.Status
	 * @return  the value of lz_usergamerecord.Status
	 * @mbg.generated  Mon Jul 08 10:44:28 CST 2019
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lz_usergamerecord.Status
	 * @param status  the value for lz_usergamerecord.Status
	 * @mbg.generated  Mon Jul 08 10:44:28 CST 2019
	 */
	public void setStatus(String status) {
		this.status = status;
	}
}