package com.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class LzWeightset {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_weightset.WeiID
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private Integer weiid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_weightset.TotalLimit
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private BigDecimal totallimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_weightset.Ratio
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private BigDecimal ratio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_weightset.PerLimit
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private BigDecimal perlimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_weightset.Createtime
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_weightset.Realtotal
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private BigDecimal realtotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_weightset.Status
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_weightset.WeiID
     *
     * @return the value of lz_weightset.WeiID
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public Integer getWeiid() {
        return weiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_weightset.WeiID
     *
     * @param weiid the value for lz_weightset.WeiID
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setWeiid(Integer weiid) {
        this.weiid = weiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_weightset.TotalLimit
     *
     * @return the value of lz_weightset.TotalLimit
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public BigDecimal getTotallimit() {
        return totallimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_weightset.TotalLimit
     *
     * @param totallimit the value for lz_weightset.TotalLimit
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setTotallimit(BigDecimal totallimit) {
        this.totallimit = totallimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_weightset.Ratio
     *
     * @return the value of lz_weightset.Ratio
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public BigDecimal getRatio() {
        return ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_weightset.Ratio
     *
     * @param ratio the value for lz_weightset.Ratio
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setRatio(BigDecimal ratio) {
        this.ratio = ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_weightset.PerLimit
     *
     * @return the value of lz_weightset.PerLimit
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public BigDecimal getPerlimit() {
        return perlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_weightset.PerLimit
     *
     * @param perlimit the value for lz_weightset.PerLimit
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setPerlimit(BigDecimal perlimit) {
        this.perlimit = perlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_weightset.Createtime
     *
     * @return the value of lz_weightset.Createtime
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_weightset.Createtime
     *
     * @param createtime the value for lz_weightset.Createtime
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_weightset.Realtotal
     *
     * @return the value of lz_weightset.Realtotal
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public BigDecimal getRealtotal() {
        return realtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_weightset.Realtotal
     *
     * @param realtotal the value for lz_weightset.Realtotal
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setRealtotal(BigDecimal realtotal) {
        this.realtotal = realtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_weightset.Status
     *
     * @return the value of lz_weightset.Status
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_weightset.Status
     *
     * @param status the value for lz_weightset.Status
     *
     * @mbg.generated Mon Jun 24 11:44:52 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }
}