package com.pojo;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
@JsonIgnoreProperties(value={"weightsetid","status","weightsetid","dealtime"})
public class LzWeightaccount {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lz_weightaccount.WeiaccID
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	private Integer weiaccid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lz_weightaccount.Phone
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lz_weightaccount.dealType
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	private String dealtype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lz_weightaccount.Weight
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	private BigDecimal weight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lz_weightaccount.weightSetId
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	private Integer weightsetid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lz_weightaccount.Dealtime
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	private Date dealtime;
	
	private String dealtimeString;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lz_weightaccount.Status
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	private String status;

	public String getDealtimeString() {
		if(dealtime!=null){
			SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
			return sdf.format(dealtime);
		}
		return "";
	}

	public void setDealtimeString(String dealtimeString) {
		this.dealtimeString = dealtimeString;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lz_weightaccount.WeiaccID
	 * @return  the value of lz_weightaccount.WeiaccID
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	public Integer getWeiaccid() {
		return weiaccid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lz_weightaccount.WeiaccID
	 * @param weiaccid  the value for lz_weightaccount.WeiaccID
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	public void setWeiaccid(Integer weiaccid) {
		this.weiaccid = weiaccid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lz_weightaccount.Phone
	 * @return  the value of lz_weightaccount.Phone
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lz_weightaccount.Phone
	 * @param phone  the value for lz_weightaccount.Phone
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lz_weightaccount.dealType
	 * @return  the value of lz_weightaccount.dealType
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	public String getDealtype() {
		return dealtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lz_weightaccount.dealType
	 * @param dealtype  the value for lz_weightaccount.dealType
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	public void setDealtype(String dealtype) {
		this.dealtype = dealtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lz_weightaccount.Weight
	 * @return  the value of lz_weightaccount.Weight
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	public BigDecimal getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lz_weightaccount.Weight
	 * @param weight  the value for lz_weightaccount.Weight
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lz_weightaccount.weightSetId
	 * @return  the value of lz_weightaccount.weightSetId
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	public Integer getWeightsetid() {
		return weightsetid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lz_weightaccount.weightSetId
	 * @param weightsetid  the value for lz_weightaccount.weightSetId
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	public void setWeightsetid(Integer weightsetid) {
		this.weightsetid = weightsetid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lz_weightaccount.Dealtime
	 * @return  the value of lz_weightaccount.Dealtime
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	public Date getDealtime() {
		return dealtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lz_weightaccount.Dealtime
	 * @param dealtime  the value for lz_weightaccount.Dealtime
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	public void setDealtime(Date dealtime) {
		this.dealtime = dealtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lz_weightaccount.Status
	 * @return  the value of lz_weightaccount.Status
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lz_weightaccount.Status
	 * @param status  the value for lz_weightaccount.Status
	 * @mbg.generated  Thu Jul 04 15:46:20 CST 2019
	 */
	public void setStatus(String status) {
		this.status = status;
	}
}